-- Create enum for session status
CREATE TYPE public.session_status AS ENUM ('draft', 'live', 'ended');

-- Create enum for SRT mode
CREATE TYPE public.srt_mode AS ENUM ('caller', 'listener');

-- Create enum for app roles
CREATE TYPE public.app_role AS ENUM ('owner', 'commenter', 'viewer');

-- Create enum for stream health
CREATE TYPE public.stream_health AS ENUM ('ok', 'warning', 'error', 'off');

-- Profiles table for user information
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Sessions table
CREATE TABLE public.sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'QC',
  status session_status NOT NULL DEFAULT 'draft',
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Session inputs (SRT configurations)
CREATE TABLE public.session_inputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
  position INTEGER NOT NULL CHECK (position >= 1 AND position <= 4),
  name TEXT NOT NULL,
  mode srt_mode NOT NULL DEFAULT 'caller',
  host TEXT,
  port INTEGER,
  passphrase TEXT,
  latency_ms INTEGER DEFAULT 200,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(session_id, position)
);

-- Session streams (playback URLs generated by backend)
CREATE TABLE public.session_streams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  input_id UUID REFERENCES public.session_inputs(id) ON DELETE CASCADE NOT NULL UNIQUE,
  webrtc_url TEXT,
  health stream_health NOT NULL DEFAULT 'off',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- User roles table (separate as per security requirements)
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE(user_id, role)
);

-- Session members (participants)
CREATE TABLE public.session_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL DEFAULT 'viewer',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(session_id, user_id)
);

-- Session invites
CREATE TABLE public.session_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
  token TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(16), 'hex'),
  role app_role NOT NULL DEFAULT 'viewer',
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
  max_uses INTEGER,
  use_count INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Session notes (collaborative markdown)
CREATE TABLE public.session_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL UNIQUE,
  content TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Session markers (QC markers on timeline)
CREATE TABLE public.session_markers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE NOT NULL,
  input_id UUID REFERENCES public.session_inputs(id) ON DELETE CASCADE,
  timestamp_ms BIGINT NOT NULL,
  label TEXT NOT NULL,
  severity stream_health NOT NULL DEFAULT 'warning',
  note TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stream metrics latest (current metrics per input)
CREATE TABLE public.stream_metrics_latest (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  input_id UUID REFERENCES public.session_inputs(id) ON DELETE CASCADE NOT NULL UNIQUE,
  video_codec TEXT,
  video_resolution TEXT,
  video_fps DECIMAL(5,2),
  video_bitrate_kbps INTEGER,
  network_rtt_ms INTEGER,
  network_packet_loss DECIMAL(5,2),
  network_retransmits INTEGER,
  network_jitter_ms INTEGER,
  audio_lufs_m DECIMAL(5,1),
  audio_lufs_s DECIMAL(5,1),
  audio_lufs_i DECIMAL(5,1),
  audio_peak_db DECIMAL(5,1),
  audio_true_peak_db DECIMAL(5,1),
  audio_channels TEXT,
  audio_sample_rate INTEGER,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stream metrics points (time-series for charts)
CREATE TABLE public.stream_metrics_points (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  input_id UUID REFERENCES public.session_inputs(id) ON DELETE CASCADE NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
  bitrate_kbps INTEGER,
  packet_loss DECIMAL(5,2),
  rtt_ms INTEGER,
  lufs_m DECIMAL(5,1)
);

-- Create index for time-series queries
CREATE INDEX idx_metrics_points_input_time ON public.stream_metrics_points(input_id, timestamp DESC);
CREATE INDEX idx_session_members_user ON public.session_members(user_id);
CREATE INDEX idx_session_members_session ON public.session_members(session_id);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_inputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_markers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stream_metrics_latest ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stream_metrics_points ENABLE ROW LEVEL SECURITY;

-- Security definer function to check session membership
CREATE OR REPLACE FUNCTION public.is_session_member(_user_id UUID, _session_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.sessions WHERE id = _session_id AND owner_id = _user_id
    UNION
    SELECT 1 FROM public.session_members WHERE session_id = _session_id AND user_id = _user_id
  )
$$;

-- Security definer function to check session role
CREATE OR REPLACE FUNCTION public.get_session_role(_user_id UUID, _session_id UUID)
RETURNS app_role
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN EXISTS (SELECT 1 FROM public.sessions WHERE id = _session_id AND owner_id = _user_id) THEN 'owner'::app_role
    ELSE (SELECT role FROM public.session_members WHERE session_id = _session_id AND user_id = _user_id)
  END
$$;

-- Security definer function to check if user has specific role
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role
  )
$$;

-- Profiles policies
CREATE POLICY "Users can view all profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Sessions policies
CREATE POLICY "Users can view owned sessions" ON public.sessions FOR SELECT TO authenticated 
  USING (owner_id = auth.uid() OR public.is_session_member(auth.uid(), id));
CREATE POLICY "Users can create sessions" ON public.sessions FOR INSERT TO authenticated 
  WITH CHECK (owner_id = auth.uid());
CREATE POLICY "Owners can update sessions" ON public.sessions FOR UPDATE TO authenticated 
  USING (owner_id = auth.uid());
CREATE POLICY "Owners can delete sessions" ON public.sessions FOR DELETE TO authenticated 
  USING (owner_id = auth.uid());

-- Session inputs policies
CREATE POLICY "Members can view inputs" ON public.session_inputs FOR SELECT TO authenticated 
  USING (public.is_session_member(auth.uid(), session_id));
CREATE POLICY "Owners can manage inputs" ON public.session_inputs FOR INSERT TO authenticated 
  WITH CHECK (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));
CREATE POLICY "Owners can update inputs" ON public.session_inputs FOR UPDATE TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));
CREATE POLICY "Owners can delete inputs" ON public.session_inputs FOR DELETE TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));

-- Session streams policies
CREATE POLICY "Members can view streams" ON public.session_streams FOR SELECT TO authenticated 
  USING (EXISTS (
    SELECT 1 FROM public.session_inputs si 
    WHERE si.id = input_id AND public.is_session_member(auth.uid(), si.session_id)
  ));

-- User roles policies (restricted access)
CREATE POLICY "Users can view own roles" ON public.user_roles FOR SELECT TO authenticated 
  USING (user_id = auth.uid());

-- Session members policies
CREATE POLICY "Members can view session members" ON public.session_members FOR SELECT TO authenticated 
  USING (public.is_session_member(auth.uid(), session_id));
CREATE POLICY "Owners can add members" ON public.session_members FOR INSERT TO authenticated 
  WITH CHECK (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));
CREATE POLICY "Owners can remove members" ON public.session_members FOR DELETE TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));

-- Session invites policies
CREATE POLICY "Members can view invites" ON public.session_invites FOR SELECT TO authenticated 
  USING (public.is_session_member(auth.uid(), session_id));
CREATE POLICY "Owners can create invites" ON public.session_invites FOR INSERT TO authenticated 
  WITH CHECK (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));
CREATE POLICY "Owners can delete invites" ON public.session_invites FOR DELETE TO authenticated 
  USING (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));
CREATE POLICY "Anyone can read invite by token" ON public.session_invites FOR SELECT TO authenticated 
  USING (true);

-- Session notes policies
CREATE POLICY "Members can view notes" ON public.session_notes FOR SELECT TO authenticated 
  USING (public.is_session_member(auth.uid(), session_id));
CREATE POLICY "Commenters can update notes" ON public.session_notes FOR UPDATE TO authenticated 
  USING (public.get_session_role(auth.uid(), session_id) IN ('owner', 'commenter'));
CREATE POLICY "Owners can insert notes" ON public.session_notes FOR INSERT TO authenticated 
  WITH CHECK (EXISTS (SELECT 1 FROM public.sessions WHERE id = session_id AND owner_id = auth.uid()));

-- Session markers policies
CREATE POLICY "Members can view markers" ON public.session_markers FOR SELECT TO authenticated 
  USING (public.is_session_member(auth.uid(), session_id));
CREATE POLICY "Commenters can create markers" ON public.session_markers FOR INSERT TO authenticated 
  WITH CHECK (public.get_session_role(auth.uid(), session_id) IN ('owner', 'commenter'));
CREATE POLICY "Commenters can update markers" ON public.session_markers FOR UPDATE TO authenticated 
  USING (public.get_session_role(auth.uid(), session_id) IN ('owner', 'commenter'));
CREATE POLICY "Owners can delete markers" ON public.session_markers FOR DELETE TO authenticated 
  USING (public.get_session_role(auth.uid(), session_id) = 'owner');

-- Stream metrics latest policies
CREATE POLICY "Members can view metrics" ON public.stream_metrics_latest FOR SELECT TO authenticated 
  USING (EXISTS (
    SELECT 1 FROM public.session_inputs si 
    WHERE si.id = input_id AND public.is_session_member(auth.uid(), si.session_id)
  ));

-- Stream metrics points policies
CREATE POLICY "Members can view metrics points" ON public.stream_metrics_points FOR SELECT TO authenticated 
  USING (EXISTS (
    SELECT 1 FROM public.session_inputs si 
    WHERE si.id = input_id AND public.is_session_member(auth.uid(), si.session_id)
  ));

-- Trigger for updated_at timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles 
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_sessions_updated_at BEFORE UPDATE ON public.sessions 
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_session_inputs_updated_at BEFORE UPDATE ON public.session_inputs 
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_session_streams_updated_at BEFORE UPDATE ON public.session_streams 
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Enable realtime for collaborative features
ALTER PUBLICATION supabase_realtime ADD TABLE public.session_notes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.session_markers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.session_members;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stream_metrics_latest;

-- Auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-create notes when session is created
CREATE OR REPLACE FUNCTION public.handle_new_session()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.session_notes (session_id, content, updated_by)
  VALUES (NEW.id, '', NEW.owner_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;